### ISSUE TITLE
Adding more tests

### ISSUE THREAD

**Issue by sletz** [Fr0stbyteR/faust2webaudio#1]
You could possibly add more tests to cover all 4 cases: SP in mono and poly modes, AudioWorklet in modo and poly modes

**Comment by Fr0stbyteR** [comment]
> You could possibly add more tests to cover all 4 cases: SP in mono and poly modes, AudioWorklet in modo and poly modes

Now you have all four modes separately in tests.

**Comment by sletz** [comment]
<img width="1265" alt="Capture d’écran 2019-03-21 à 17 13 54" src="https://user-images.githubusercontent.com/1430487/54767115-cde9bc80-4bfc-11e9-81bc-ff55acdf16ea.png">

Got errors with Chrome

**Comment by Fr0stbyteR** [comment]
> 
> Got errors with Chrome

I think you put the ./test subfolder in server which doesn't contain the js. Maybe try to run the server with the whole project folder instead.

**Comment by sletz** [comment]
Correct ((-;
