### ISSUE TITLE
Calling window.node.allNotesOff()

### ISSUE THREAD

**Issue by ghost** [Fr0stbyteR/faust2webaudio#10]
Hello!
First of all, amazing repository!

Got an issue on FaustAudioWorkletNode.
I am sending messages to the faust node inside an AudioWorkletNode using -> window.node.<function>
The window.node.allNotesOff() seems to be not working, I am using destroy() for the moment. 

https://github.com/Fr0stbyteR/faust2webaudio/blob/f72d0a3f14b348016199d93a4c3d64304b1f7682/src/FaustAudioWorkletNode.ts

All the others seem to be working fine!

Thanks,
Luis

**Comment by sletz** [comment]
Fixed in GRAME faust2webaudio version here https://github.com/grame-cncm/faust2webaudio/commit/b64277eb812f9aa6eafafa43532d287fc63a6617.

**Comment by ghost** [comment]
Thanks!
